#!/usr/bin/env python3
"""Phase 2: Knowledge fusion - merge all sources onto outline skeleton."""
import os
import sys
import json
import re


def load_extracted(extracted_dir):
    """Load all extracted text files."""
    texts = {}
    for fname in sorted(os.listdir(extracted_dir)):
        if fname.endswith(".txt"):
            path = os.path.join(extracted_dir, fname)
            with open(path, "r", encoding="utf-8") as f:
                texts[fname] = f.read()
    return texts


def identify_concepts(text, chapter):
    """Identify key concepts from PPT text using heading patterns."""
    concepts = []
    lines = text.split("\n")
    current_concept = None
    current_content = []

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # Detect concept starts (numbered items, bold topics, etc.)
        if re.match(r"^\d+[\.\)]\s+\*\*", line) or re.match(
            r"^[A-Z][a-z].*:(\s|$)", line
        ):
            if current_concept:
                concepts.append(
                    {
                        "name": current_concept,
                        "content": "\n".join(current_content),
                    }
                )
            current_concept = line
            current_content = []
        elif re.match(r"^(Slide|---|\d+\)|Key Points)", line):
            if current_concept:
                concepts.append(
                    {
                        "name": current_concept,
                        "content": "\n".join(current_content),
                    }
                )
            current_concept = None
            current_content = []
        else:
            current_content.append(line)

    if current_concept:
        concepts.append(
            {"name": current_concept, "content": "\n".join(current_content)}
        )

    return concepts


def generate_source_tag(sources):
    """Generate a source tag from dict of sources."""
    parts = []
    for src_type, src_val in sources.items():
        if src_val:
            parts.append(f"{src_type}: {src_val}")
    return " | ".join(parts) if parts else ""


def fuse_all(course_dir):
    """Run the complete knowledge fusion pipeline."""
    extracted_dir = os.path.join(course_dir, "__extracted__")
    texts = load_extracted(extracted_dir)

    output = []
    output.append("# 期末复习资料\n")
    output.append("> Generated by final-exam-review skill\n")

    for fname, text in texts.items():
        ch_name = os.path.splitext(fname)[0]
        output.append(f"\n## {ch_name}\n")
        output.append(f"> Source: {fname}\n")

        concepts = identify_concepts(text, ch_name)
        for c in concepts:
            if c["content"].strip():
                output.append(f"\n### {c['name']}\n")
                output.append(c["content"])
                output.append("")

    fused_path = os.path.join(course_dir, "_fused_review.md")
    with open(fused_path, "w", encoding="utf-8") as f:
        f.write("\n".join(output))

    print(f"Fused review saved to {fused_path}")
    return fused_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 fuse_knowledge.py <course_directory>")
        sys.exit(1)

    fuse_all(sys.argv[1])
